### PR TITLE
Learn about Spoke's newest features on the What's New page

### PR DESCRIPTION
**Pull request by brianpeiris**
Check out "What's New" page for the latest and greatest!

firefox_2019-07-24_22-21-38

Also added a "Latest Update" panel to the Projects page, if you're not a new user.

firefox_2019-07-24_22-21-55

### CODE REVIEW

**Comment by brianpeiris** [comment]
I'm wasn't familiar with styled-components, so maybe I did it wrong. You'll probably also want to tweak the styling and layout of things, so feel free to commit directly to this branch.

**Comment by brianpeiris** [comment]
For testing, you can change the filter on this line to see non-whats-new PRs https://github.com/mozilla/Spoke/pull/712/files#diff-e9ded5b1ea965e2ca628201256bea3efR41

**Comment by robertlong** [comment]
Awesome! Thanks for doing this!

**Comment by brianpeiris** [comment]
@robertlong let me know if I can do anything to unblock this merge.

**Comment by robertlong** [comment]
I just need to add some design polish to the project page component. I'll get right on it and merge today.

**Pull request merged**
