### PR TITLE
Use normalize-wheel package to fix scroll speed

### LINKED ISSUE #839: Mouse scrolling in the viewport is too extreme
I haven't done anything specific to my mouse settings (and the scrolling is fine / normal in other applications) but now when I use the mouse wheel in Spoke, the view port scrolling is too extreme. 

Video shows what two scroll 'notches' results in when the ground mesh is selected from the 'Wide Open Space' template, but this also happens when selecting spawn points. 

https://vimeo.com/371921522

Firefox Stable 70.0.1, Windows

### PR DESCRIPTION
**Pull request by robertlong**
Fixes #839

### CODE REVIEW

**Comment by misslivirose** [comment]
Testing now - had to update some stuff on my laptop

**Comment by misslivirose** [comment]
What I see now is that it zooms out (not quite as far, but still out) and then zooms back in to a closer distance

**Comment by misslivirose** [comment]
Hm, yeah, after testing more, I think that the experience of it auto-zooming is less preferable than the original issue, although both of them are quite difficult to work around. I've never had this issue with this mouse before trying it on this computer, and I've checked the scroll settings to see if anything seemed off but other pages are okay.

**Comment by robertlong** [comment]
Ok, sounds like there's some work to be done. Let's test more when you're back.

**Comment by misslivirose** [comment]
I suspect that this is something to do with this particular mouse driver - it's started acting up in other applications too on this PC, but I don't see this mouse issue in Spoke on other PCs / with other mice.

**Comment by robertlong** [comment]
I think @InfiniteLee saw it with Windows smooth scrolling turned on. Maybe try enabling / disabling that?

**Comment by misslivirose** [comment]
The mouse settings seemed the same on both computers that I tested - I can try to dig a little more, but so far no leads.

**Comment by misslivirose** [comment]
I had to download and turn off smooth scrolling directly through the mouse software (changing the Windows settings and Firefox settings didn't work, but turning it off through the mouse customization app did)

Logitech M185 mouse. One I turned smooth scrolling off through the Logitech software, production Spoke was fine

**Comment by robertlong** [comment]
I'm going to close this PR. If we have more issues with scrolling we can look into it again.

**Pull request closed without merging**
